[theme]
base                     = "light"
primaryColor             = "#E8281F"
backgroundColor          = "#F4F5F7"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#1A1A1A"
font                     = "sans serif"

[server]
maxUploadSize = 50
headless      = true

[browser]
gatherUsageStats = false
